import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
// @ts-expect-error — plain .mjs build script, no types
import { computeNativeFingerprint, isNativePlugin } from '../../scripts/nativeFingerprint.mjs';

/*
 * The guard on over-the-air updates.
 *
 * A bundle can only replace the web layer, so if its JS calls a plugin the installed APK was never
 * compiled with, the app white-screens. The fingerprint is what stops that: when it changes, OTA is
 * skipped and the app asks for a new APK instead.
 *
 * Which makes a plugin this misses genuinely dangerous, and invisible — nothing fails at build
 * time, nothing fails in CI, and the app keeps updating itself right up until the bundle reaches
 * for something that isn't there. It had exactly that hole: the predicate listed three npm scopes,
 * and @transistorsoft/capacitor-background-fetch is in a fourth.
 */

const read = (relativePath: string) =>
  readFileSync(fileURLToPath(new URL(relativePath, import.meta.url)), 'utf8');

/**
 * The native plugin modules Capacitor actually compiles into the APK, taken from the file it
 * generates for Gradle. Tracked in git, unlike capacitor.plugins.json, so this works from a clean
 * checkout — and regenerated by `cap sync`, so it updates itself when a plugin is added.
 */
const registeredPackages = (): string[] => {
  const gradle = read('../../android/capacitor.settings.gradle');
  return [...gradle.matchAll(/node_modules\/(@[^/]+\/[^/']+)/g)].map((match) => match[1]);
};

describe('isNativePlugin', () => {
  it('matches every plugin Capacitor compiles into the APK', () => {
    const missed = registeredPackages().filter((pkg) => !isNativePlugin(pkg));
    // Named in the failure rather than just counted: the fix is to make the predicate cover
    // whatever is listed here, and the list is the whole diagnosis.
    expect(missed).toEqual([]);
  });

  it('covers plugins from outside the three original scopes', () => {
    // The two that were silently invisible. Kept as explicit cases so a future narrowing of the
    // predicate fails on the exact packages that motivated widening it.
    expect(isNativePlugin('@transistorsoft/capacitor-background-fetch')).toBe(true);
    expect(isNativePlugin('@aparajita/capacitor-biometric-auth')).toBe(true);
  });

  it('ignores dependencies with no native side', () => {
    // Over-inclusion is the safe direction — it costs an unnecessary APK prompt, where
    // under-inclusion white-screens the app — but the predicate should not sweep in everything.
    for (const pkg of ['react', 'dexie', 'zod', '@tanstack/react-query', 'framer-motion']) {
      expect(isNativePlugin(pkg)).toBe(false);
    }
  });
});

describe('computeNativeFingerprint', () => {
  it('is stable across calls', () => {
    // Two builds of the same commit must agree, or every release would demand a new APK.
    expect(computeNativeFingerprint()).toBe(computeNativeFingerprint());
  });

  it('is a short hex digest', () => {
    expect(computeNativeFingerprint()).toMatch(/^[0-9a-f]{12}$/);
  });
});
