import { randomUUID } from 'node:crypto';
import type { WSContext } from 'hono/ws';
import { trackEvent } from '../lib/telemetry';

/* Live sync: one WebSocket per open client. Whenever a user's data changes,
   every OTHER client of the same user gets a "changed" nudge and pulls. */

interface LiveClient {
  ws: WSContext;
  /** Random id generated by each client session, echoed on its REST calls. */
  clientId: string;
}

const clients = new Map<string, Set<LiveClient>>();

/* WebSocket URLs end up in access logs, so they must never carry the session
   token. Instead the client redeems a single-use, 30-second ticket issued over
   a normally-authenticated REST call. */

const TICKET_TTL_MS = 30_000;
const tickets = new Map<string, { userId: string; expires: number }>();

export function issueWsTicket(userId: string): string {
  const now = Date.now();
  for (const [key, value] of tickets) if (value.expires < now) tickets.delete(key);
  const ticket = randomUUID();
  tickets.set(ticket, { userId, expires: now + TICKET_TTL_MS });
  return ticket;
}

/** Single-use: the ticket is consumed whether or not it is still valid. */
export function redeemWsTicket(ticket: string): string | null {
  const entry = tickets.get(ticket);
  tickets.delete(ticket);
  if (!entry || entry.expires < Date.now()) {
    /* A failed redeem should be close to impossible in normal use: the client requests a ticket
       and opens the socket immediately, well inside thirty seconds. So the two reasons it fails
       are worth separating and both are worth knowing about. `expired` at any volume means clients
       are being delayed between the two calls — a slow network or a backgrounded webview — and
       live sync is quietly not working for them. `unknown` means a ticket this process never
       issued, which is either someone guessing at the endpoint or, far more likely, the first
       symptom of a second container: these tickets are in-memory, so a second instance would fail
       every redeem that did not land on the process that issued it. */
    trackEvent('live_ws_ticket_rejected', { reason: entry ? 'expired' : 'unknown' });
    return null;
  }
  return entry.userId;
}

export function addLiveClient(userId: string, clientId: string, ws: WSContext): void {
  let set = clients.get(userId);
  if (!set) {
    set = new Set();
    clients.set(userId, set);
  }
  set.add({ ws, clientId });
}

export function removeLiveClient(userId: string, ws: WSContext): void {
  const set = clients.get(userId);
  if (!set) return;
  for (const client of set) {
    if (client.ws === ws) set.delete(client);
  }
  if (set.size === 0) clients.delete(userId);
}

/* Gauges for the once-a-minute runtime_metrics row (wired up in index.ts).
 *
 * Both maps are unbounded in principle and swept only by their own logic — `clients` by socket
 * close, `tickets` by the next issue — so these two numbers are also how a leak in either would
 * ever be noticed: sockets that never close, or tickets issued to clients that never connect.
 * Reported from the metrics loop rather than on change, because a gauge is a level, not an event. */
export const liveSyncGauges = () => ({
  ws_users: clients.size,
  ws_clients: [...clients.values()].reduce((total, set) => total + set.size, 0),
  ws_tickets_outstanding: tickets.size,
});

/** Tell the user's other devices that something changed (skips the originator). */
export function notifyUserChanged(userId: string, exceptClientId?: string | null): void {
  const set = clients.get(userId);
  if (!set) return;
  for (const client of set) {
    if (exceptClientId && client.clientId === exceptClientId) continue;
    try {
      client.ws.send('changed');
    } catch {
      // a dying socket must never break the request that triggered the notify
    }
  }
}
