import { randomUUID } from 'node:crypto';
import type { WSContext } from 'hono/ws';

/* Live sync: one WebSocket per open client. Whenever a user's data changes,
   every OTHER client of the same user gets a "changed" nudge and pulls. */

interface LiveClient {
  ws: WSContext;
  /** Random id generated by each client session, echoed on its REST calls. */
  clientId: string;
}

const clients = new Map<string, Set<LiveClient>>();

/* WebSocket URLs end up in access logs, so they must never carry the session
   token. Instead the client redeems a single-use, 30-second ticket issued over
   a normally-authenticated REST call. */

const TICKET_TTL_MS = 30_000;
const tickets = new Map<string, { userId: string; expires: number }>();

export function issueWsTicket(userId: string): string {
  const now = Date.now();
  for (const [key, value] of tickets) if (value.expires < now) tickets.delete(key);
  const ticket = randomUUID();
  tickets.set(ticket, { userId, expires: now + TICKET_TTL_MS });
  return ticket;
}

/** Single-use: the ticket is consumed whether or not it is still valid. */
export function redeemWsTicket(ticket: string): string | null {
  const entry = tickets.get(ticket);
  tickets.delete(ticket);
  if (!entry || entry.expires < Date.now()) return null;
  return entry.userId;
}

export function addLiveClient(userId: string, clientId: string, ws: WSContext): void {
  let set = clients.get(userId);
  if (!set) {
    set = new Set();
    clients.set(userId, set);
  }
  set.add({ ws, clientId });
}

export function removeLiveClient(userId: string, ws: WSContext): void {
  const set = clients.get(userId);
  if (!set) return;
  for (const client of set) {
    if (client.ws === ws) set.delete(client);
  }
  if (set.size === 0) clients.delete(userId);
}

/** Tell the user's other devices that something changed (skips the originator). */
export function notifyUserChanged(userId: string, exceptClientId?: string | null): void {
  const set = clients.get(userId);
  if (!set) return;
  for (const client of set) {
    if (exceptClientId && client.clientId === exceptClientId) continue;
    try {
      client.ws.send('changed');
    } catch {
      // a dying socket must never break the request that triggered the notify
    }
  }
}
