import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'es.tablerus.diary',
  appName: 'Diary',
  webDir: 'dist',
  // Capacitor's native bridge otherwise logs every plugin call (id, method, args) at
  // verbose level in debug builds — e.g. LocalNotifications.getPending() on every
  // refreshNotifications() reconcile. Silence it globally rather than per-call.
  android: {
    loggingBehavior: 'none',
  },
  plugins: {
    SplashScreen: {
      // The native splash is a plain themed background; the animated logo
      // lives in the web boot overlay (index.html), which takes over instantly.
      launchShowDuration: 200,
      // launchShowDuration: 0,
      launchAutoHide: true,
      backgroundColor: '#18181b',
    },
    LocalNotifications: {
      /* Resolved by name at runtime (getIdentifier), which means nothing in the build can see the
         reference: the drawable is generated by web/scripts/generateAssets.ts and kept out of the
         release build's resource shrinker by android/app/src/main/res/raw/keep.xml. Without that
         keep rule the plugin silently substitutes Android's ⓘ. */
      smallIcon: 'ic_stat_notify',
      // Only the alpha of smallIcon survives; this is the tint Android applies to the silhouette.
      iconColor: '#0072FF',
    },
    CapacitorUpdater: {
      // Manual mode: web/src/lib/liveUpdate.ts decides what to download and when to apply it,
      // and the bundles come from our own GitHub release. The plugin never contacts Capgo.
      autoUpdate: false,
      // A bundle that does not reach notifyAppReady() within this window is assumed broken and
      // is automatically rolled back to the last working one. This is the OTA safety net.
      appReadyTimeout: 10_000,
    },
  },
};

export default config;
